# Indexing, Selection, and Editing of Datasets

In [1]:
import pandas as pd

In [46]:
book = pd.read_csv("books.csv")

In [47]:
book

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...
...,...,...,...,...,...,...,...,...
95,96,First Little Readers Parent Pack: Guided Readi...,11.40,4.7,Deborah Schecter,2010,Nonfiction,amazon.com/First-Little-Readers-Parent-Pack/dp...
96,97,Hatchet,5.14,4.7,Gary Paulsen,1987,"young adult novel, adventure novel, survival ...",amazon.com/Hatchet-Gary-Paulsen/dp/1416936475/...
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...
99,100,The Wonky Donkey,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...

### Built-in Selection Methods

In [48]:
book.Rank

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Name: Rank, Length: 100, dtype: int64

In [49]:
book['Rank']

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Name: Rank, Length: 100, dtype: int64

In [50]:
book['Rank'] [3]

np.int64(4)

### Index-based Selection

In [51]:
book.iloc[0]

Rank                                                                   1
book title                                  Iron Flame (The Empyrean, 2)
book price                                                         18.42
rating                                                               4.1
author                                                    Rebecca Yarros
year of publication                                                 2023
genre                                                    Fantasy Romance
url                    amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
Name: 0, dtype: object

In [52]:
book.iloc[:,1]

0                          Iron Flame (The Empyrean, 2)
1                                       The Woman in Me
2                                     My Name Is Barbra
3     Friends, Lovers, and the Big Terrible Thing: A...
4                                 How to Catch a Turkey
                            ...
95    First Little Readers Parent Pack: Guided Readi...
96                                              Hatchet
97    The Wager: A Tale of Shipwreck, Mutiny and Murder
98    I'm Dead, Now What?: Important Information Abo...
99                                     The Wonky Donkey
Name: book title, Length: 100, dtype: str

In [54]:
book.iloc[:3, 1]

0    Iron Flame (The Empyrean, 2)
1                 The Woman in Me
2               My Name Is Barbra
Name: book title, dtype: str

In [55]:
book.iloc[1:4, 1]

1                                      The Woman in Me
2                                    My Name Is Barbra
3    Friends, Lovers, and the Big Terrible Thing: A...
Name: book title, dtype: str

In [56]:
book.iloc[1:5:2, 1]

1                                      The Woman in Me
3    Friends, Lovers, and the Big Terrible Thing: A...
Name: book title, dtype: str

In [59]:
book.iloc[:4]

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...

In [61]:
book.iloc[-4:]

,Rank,book title,book price,rating,author,year of publication,genre,url
96,97,Hatchet,5.14,4.7,Gary Paulsen,1987,"young adult novel, adventure novel, survival ...",amazon.com/Hatchet-Gary-Paulsen/dp/1416936475/...
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...
99,100,The Wonky Donkey,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...

In [64]:
book.loc[0, 'author']

'Rebecca Yarros'

In [67]:
book.loc[:,['rating','author','year of publication']]

    rating              author  year of publication
0      4.1      Rebecca Yarros                 2023
1      4.5      Britney Spears                 2023
2      4.5    Barbra Streisand                 2023
3      4.4       Matthew Perry                 2023
4      4.8        Adam Wallace                 2018
..     ...                 ...                  ...
95     4.7    Deborah Schecter                 2010
96     4.7        Gary Paulsen                 1987
97     4.5         David Grann                 2023
98     4.6  Peter Pauper Press                 2015
99     4.8         Craig Smith                 2009

[100 rows x 3 columns]

In [68]:
book.loc[:5,['rating','author','year of publication']]

   rating            author  year of publication
0     4.1    Rebecca Yarros                 2023
1     4.5    Britney Spears                 2023
2     4.5  Barbra Streisand                 2023
3     4.4     Matthew Perry                 2023
4     4.8      Adam Wallace                 2018
5     4.8    Rebecca Yarros                 2023

In [72]:
book.loc[1:100:11,['rating','author','year of publication']]

    rating                  author  year of publication
1      4.5          Britney Spears                 2023
12     4.8             James Clear                 2018
23     4.5        Hanya Yanagihara                 2015
34     4.9            David Brooks                 2023
45     NaN           Nicole LePera                 2023
56     4.8              Snoop Dogg                 2018
67     4.7  School Zone Publishing                 1994
78     4.6         Shelby Van Pelt                 2024
89     4.9            J.K. Rowling                 1999

In [75]:
book.set_index("book title")

,Rank,book price,rating,author,year of publication,genre,url
book title,,,,,,,
"Iron Flame (The Empyrean, 2)",1,18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
The Woman in Me,2,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
My Name Is Barbra,3,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
"Friends, Lovers, and the Big Terrible Thing: A Memoir",4,23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
How to Catch a Turkey,5,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...
...,...,...,...,...,...,...,...
First Little Readers Parent Pack: Guided Reading Level A: 25 Irresistible Books That Are Just the Right Level for Beginning R,96,11.40,4.7,Deborah Schecter,2010,Nonfiction,amazon.com/First-Little-Readers-Parent-Pack/dp...
Hatchet,97,5.14,4.7,Gary Paulsen,1987,"young adult novel, adventure novel, survival ...",amazon.com/Hatchet-Gary-Paulsen/dp/1416936475/...
"The Wager: A Tale of Shipwreck, Mutiny and Murder",98,15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...
"I'm Dead, Now What?: Important Information About My Belongings, Business Affairs, and Wishes",99,12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...
The Wonky Donkey,100,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...

In [80]:
pmean=book['book price'].mean()
print("Середня ціна =",pmean)
book.loc[book['book price']>pmean]

Середня ціна = 12.7086

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
5,6,"Fourth Wing (The Empyrean, 1)",16.99,4.8,Rebecca Yarros,2023,Fantasy,amazon.com/Fourth-Wing-Empyrean-Rebecca-Yarros...
6,7,Unwoke: How to Defeat Cultural Marxism in America,27.43,4.3,Unknown,2023,"Nonfiction, Politics",amazon.com/Unwoke-Defeat-Cultural-Marxism-Amer...
12,13,Atomic Habits: An Easy & Proven Way to Build G...,13.79,4.8,James Clear,2018,"Self-improvement, Nonfiction",amazon.com/Atomic-Habits-Proven-Build-Break/dp...
14,15,The 48 Laws of Power,13.82,4.7,Robert Greene,1998,Nonfiction,amazon.com/48-Laws-Power-Robert-Greene/dp/0140...
15,16,The Great Disappearance: 31 Ways to be Rapture...,18.84,4.6,David Jeremiah,2023,"Spiritual Warfare, Biblical Studies - Prophecy...",amazon.com/Great-Disappearance-Ways-Rapture-Re...
16,17,Lessons in Chemistry: A Novel,15.37,4.6,Bonnie Garmus,2022,"Fiction, Historical Fiction",amazon.com/Lessons-Chemistry-Novel-Bonnie-Garm...
17,18,The Exchange: After The Firm (The Firm Series),18.96,4.1,John Grisham,2023,"Literary, Thrillers - Suspense",amazon.com/Exchange-After-Firm/dp/0385548958/r...
24,25,"House of Flame and Shadow (Crescent City, 3)",18.48,NaN,Sarah J. Maas,2023,"Fantasy, Dragons, Young Adult, Fiction, High F...",amazon.com/House-Flame-Shadow-Crescent-City/dp...
28,29,Murtagh: The World of Eragon (The Inheritance ...,22.48,4.8,Christopher Paolini,2023,"Fantasy, Dragons, Young Adult, Fiction, High F...",amazon.com/Murtagh-World-Eragon-Inheritance-Cy...
33,34,How to Know a Person: The Art of Seeing Others...,19.89,4.5,Alice Walstead,2022,"Thriller, mystery, suspense",amazon.com/How-Know-Person-Seeing-Others/dp/05...
40,41,Outlive: The Science and Art of Longevity,16.99,4.7,Peter Attia,2023,"Health, Nonfiction, Science, Self Help",amazon.com/Outlive-Longevity-Peter-Attia-MD/dp...
41,42,Hundred Years' War on Palestine,12.99,4.6,Rashid Khalidi,2019,"History, Nonfiction, Politics, War",amazon.com/Hundred-Years-War-Palestine-Colonia...
45,46,"How to Be the Love You Seek: Break Cycles, Fin...",20.11,NaN,Nicole LePera,2023,"Self Help, Nonfiction, Mental Health, Psycholo...",amazon.com/How-Love-You-Seek-Relationships/dp/...
46,47,A Court of Thorns and Roses Paperback Box Set ...,48.77,4.8,Sarah J. Maas,2021,"Fantasy, Romance",amazon.com/Court-Thorns-Roses-Paperback-books/...
50,51,Hidden Potential: The Science of Achieving Gre...,21.00,4.4,Adam M. Grant,2023,"Nonfiction, Self Help, Psychology, Business, L...",amazon.com/Hidden-Potential-Science-Achieving-...
51,52,Resurrection Walk (Lincoln Lawyer),20.98,5.0,Michael Connelly,2023,"Fiction, Mystery, Thriller, Suspense, Crime, L...",amazon.com/Resurrection-Walk-Michael-Connelly/...
57,58,The Shadow Work Journal: A Guide to Integrate ...,17.28,4.6,Keila Shaheen,2021,"Self Help, Psychology",amazon.com/Shadow-Work-Journal-Integrate-Trans...
58,59,Interesting Facts For Curious Minds: 1572 Rand...,12.89,4.6,Jordan Moore,2022,Nonfiction,amazon.com/Interesting-Facts-Curious-Minds-Min...
60,61,Elon Musk,20.99,4.7,Walter Isaacson,2023,"Biography, Nonfiction, Business, Technology",amazon.com/Elon-Musk-Walter-Isaacson/dp/198218...
63,64,Tom Lake: A Reese's Book Club Pick,15.33,4.3,Ann Patchett,2023,"Literary, Medical, Family Life - General, Worl...",amazon.com/Tom-Lake-Novel-Ann-Patchett/dp/0063...
64,65,The Covenant of Water (Oprah's Book Club),16.79,4.6,Abraham Verghese,2023,"Fiction, Mystery",amazon.com/Covenant-Water-Abraham-Verghese/dp/...
65,66,Dirty Thirty (30) (Stephanie Plum),20.98,4.7,Janet Evanovich,2021,"Dark, Thriller, Fantasy, Adult, Contemporary, ...",amazon.com/Dirty-Thirty-30-Stephanie-Plum/dp/1...
69,70,Haunting Adeline (Cat and Mouse Duet),13.36,4.4,H.D. Carlton,2021,"Dark, Thriller, Fantasy, Adult, Contemporary, ...",amazon.com/Haunting-Adeline-Cat-Mouse-Duet/dp/...
71,72,A Court of Mist and Fury (A Court of Thorns an...,12.79,4.8,Sarah J. Maas,2016,"Fantasy, Romance, Young Adult, New Adult, Fiction",amazon.com/Court-Mist-Fury-Thorns-Roses/dp/163...
72,73,The Creative Act: A Way of Being,17.49,4.7,Rick Rubin,2023,"Nonfiction, Art, Music, Philosophy, Self Help,...",amazon.com/Creative-Act-Way-Being/dp/059365288...
73,74,My First Library : Boxset of 10 Board Books fo...,16.74,4.6,Not available,2018,Childrens,amazon.com/My-First-Library-Boxset-Board/dp/93...
74,75,"Forever Strong: A New, Science-Based Strategy ...",20.63,4.6,Gabrielle Lyon,2023,"Health, Nonfiction, Nutrition, Fitness, Self H...",amazon.com/Forever-Strong-Science-Based-Strate...
76,77,Demon Copperhead: A Pulitzer Prize Winner,19.50,4.6,Barbara Kingsolver,2022,Fiction,amazon.com/Demon-Copperhead-Novel-Barbara-King...
77,78,Israel: A Simple Guide to the Most Misundersto...,15.59,4.7,Noa Tishby,2021,"Nonfiction, History, Politics, Israel, Jewish,...",amazon.com/Israel-Simple-Guide-Misunderstood-C...
78,79,Remarkably Bright Creatures: A Read with Jenna...,15.99,4.6,Shelby Van Pelt,2024,Fiction,amazon.com/Remarkably-Bright-Creatures-Shelby-...
79,80,Harry Potter Paperback Box Set (Books 1-7),45.22,4.9,J.K. Rowling,2014,"Childrens, Young Adult, Fantasy, Science Ficti...",amazon.com/Harry-Potter-Paperback-Box-Books/dp...
85,86,Love Comes First,17.99,NaN,Emily Giffin,2016,"Fiction, Romance, Contemporary, Audiobook, Adu...",amazon.com/Love-Comes-First-Jenna-Hager/dp/031...
86,87,The Ballad of Songbirds and Snakes (A Hunger G...,15.79,4.6,Suzanne Collins,2020,"Adventure, War, Science Fiction, Romance, Acti...",amazon.com/Ballad-Songbirds-Snakes-Hunger-Game...
88,89,The Shadow Work Journal 2nd Edition: a Guide t...,18.46,4.7,Keila Shaheen,2023,Self Help,amazon.com/Shadow-Work-Journal-2nd-Integrate/d...
89,90,Harry Potter and the Prisoner of Azkaban (Harr...,25.97,4.9,J.K. Rowling,1999,Fantasy,amazon.com/Harry-Potter-Prisoner-Azkaban-MinaL...
93,94,Percy Jackson and the Olympians: The Chalice o...,15.63,4.7,Rick Riordan,2023,"Fantasy, Adventure, Mythology",amazon.com/Percy-Jackson-Olympians-Chalice-God...
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...

In [92]:
pmean=book['book price'].mean()
print("Середня ціна =",pmean)
book.loc[(book['book price']<pmean) & (book['year of publication']==2018)]

Середня ціна = 12.7086

,Rank,book title,book price,rating,author,year of publication,genre,url
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...
13,14,Stocking Stuffer Mad Libs: World's Greatest Wo...,2.79,4.8,Leigh Olsen,2018,"Childrens, Storytime,Fiction",amazon.com/Stocking-Stuffer-Libs-Leigh-Olsen/d...
53,54,Flash Cards: Sight Words,2.88,4.8,Scholastic,2018,"Educational Material, Childrens",amazon.com/Flash-Cards-Scholastic-Teacher-Reso...
56,57,From Crook to Cook: Platinum Recipes from Tha ...,12.15,4.8,Snoop Dogg,2018,"Cookbooks, Cooking",amazon.com/Crook-Cook-Platinum-Recipes-Kitchen...
61,62,The Complete Cookbook for Young Chefs: 100+ Re...,9.97,4.8,Americas Test Kitchen Kids,2018,Cookbook,amazon.com/Complete-Cookbook-Young-Chefs/dp/14...
70,71,Verity,10.98,4.6,Colleen Hoover,2018,"Thriller, Romance, Mystery, Fiction",amazon.com/Verity-Colleen-Hoover/dp/1538724731...

In [94]:
book.loc[(book.genre=="Memoir") | (book.rating>=4.8)]

,Rank,book title,book price,rating,author,year of publication,genre,url
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...
5,6,"Fourth Wing (The Empyrean, 1)",16.99,4.8,Rebecca Yarros,2023,Fantasy,amazon.com/Fourth-Wing-Empyrean-Rebecca-Yarros...
7,8,No Brainer (Diary of a Wimpy Kid Book 18),8.55,4.8,Jeff Kinney,2023,"Humor, Middle Grade",amazon.com/Brainer-Diary-Wimpy-Kid-Book/dp/141...
11,12,Night (Night),6.26,4.7,Elie Wiesel,1960,Memoir,amazon.com/Night-Elie-Wiesel/dp/0374500010/ref...
12,13,Atomic Habits: An Easy & Proven Way to Build G...,13.79,4.8,James Clear,2018,"Self-improvement, Nonfiction",amazon.com/Atomic-Habits-Proven-Build-Break/dp...
13,14,Stocking Stuffer Mad Libs: World's Greatest Wo...,2.79,4.8,Leigh Olsen,2018,"Childrens, Storytime,Fiction",amazon.com/Stocking-Stuffer-Libs-Leigh-Olsen/d...
18,19,Taylor Swift: A Little Golden Book Biography,4.78,4.9,Wendy Loggia,2023,"Picture Books, Biography",amazon.com/Taylor-Swift-Little-Golden-Biograph...
19,20,Don't Let the Pigeon Drive the Sleigh!,11.99,4.8,Mo Willems,2023,"Picture Books, Christmas, Holiday, Humor, Chil...",amazon.com/Dont-Let-Pigeon-Drive-Sleigh/dp/145...
20,21,Turkey Trouble,8.79,4.8,Wendi Silvano,2009,"Picture Books, Childrens, Holiday, Animals, Hu...",amazon.com/Turkey-Trouble-Wendi-Silvano/dp/076...
21,22,"The Body Keeps the Score: Brain, Mind, and Bod...",9.68,4.8,Bessel van der Kolk,2014,"Nonfiction, Psychology, Self Help, Mental Heal...",amazon.com/Body-Keeps-Score-Healing-Trauma/dp/...
25,26,"World of Eric Carle, Around the Farm 30-Button...",9.43,4.8,Editors of Publications International,2013,"Childrens, Activities, Crafts, Games",amazon.com/World-Carle-Around-Play-Sound/dp/14...
26,27,"Goodnight, Goodnight Construction Site (Board ...",3.78,4.9,Sherri Duskey Rinker,2011,"Picture Book, Cars and Trucks",amazon.com/Goodnight-Construction-Sherri-Duske...
27,28,The Leaf Thief: (The Perfect Fall Book for Chi...,10.39,4.8,Alice Hemming,2021,Childrens,amazon.com/Leaf-Thief-Alice-Hemming/dp/1728235...
28,29,Murtagh: The World of Eragon (The Inheritance ...,22.48,4.8,Christopher Paolini,2023,"Fantasy, Dragons, Young Adult, Fiction, High F...",amazon.com/Murtagh-World-Eragon-Inheritance-Cy...
29,30,"Brown Bear, Brown Bear, What Do You See?",4.94,4.9,Bill Martin Jr.,1967,"Picture Book, Colors, Wild Animals",amazon.com/Brown-Bear-What-You-See/dp/08050479...
30,31,Balloons over Broadway: The True Story of the ...,12.19,4.9,Bill Martin Jr.,1967,"Childrens, literature",amazon.com/Balloons-over-Broadway-Puppeteer-Ed...
34,35,The Very Hungry Caterpillar,5.90,4.9,David Brooks,2023,Nonfiction,amazon.com/Very-Hungry-Caterpillar-Eric-Carle/...
35,36,How to Catch a Reindeer,5.99,4.8,Eric Carle,1969,"Childrens, literature",amazon.com/How-Catch-Reindeer-Alice-Walstead/d...
36,37,Pookie's Thanksgiving (Little Pookie),6.99,4.9,Alice Walstead,2022,"Childrens, literature",amazon.com/Pookies-Thanksgiving-Little-Pookie-...
39,40,I Love You to the Moon and Back,4.76,4.9,Taylor Jenkins Reid,2017,Historical Fiction,amazon.com/I-Love-You-Moon-Back/dp/1589255518/...
42,43,Little Blue Truck's Christmas: A Christmas Hol...,11.20,4.8,Alice Schertle,2014,"Childrens, literature",amazon.com/Little-Trucks-Christmas-Alice-Scher...
43,44,Goodnight Moon,5.36,4.9,Margaret Wise Brown,1947,"Childrens, literature",amazon.com/Goodnight-Moon-Margaret-Wise-Brown/...
46,47,A Court of Thorns and Roses Paperback Box Set ...,48.77,4.8,Sarah J. Maas,2021,"Fantasy, Romance",amazon.com/Court-Thorns-Roses-Paperback-books/...
47,48,Where's Bluey?: A Search-and-Find Book,6.93,4.8,Penguin Young Readers Licenses (,2022,"Childrens, Storytime,Fiction",amazon.com/Wheres-Bluey-Search-Find-Book/dp/05...
48,49,The Wonderful Things You Will Be,9.40,4.9,Emily Winfield Martin,2015,"Picture Books, Childrens, Fiction, Poetry",amazon.com/Wonderful-Things-You-Will-Be/dp/038...
49,50,How to Catch a Dinosaur,4.66,4.8,Adam Wallace,2019,"Picture Books, Dinosaurs, Childrens, Fiction, ...",amazon.com/How-Catch-Dinosaur-Adam-Wallace/dp/...
51,52,Resurrection Walk (Lincoln Lawyer),20.98,5.0,Michael Connelly,2023,"Fiction, Mystery, Thriller, Suspense, Crime, L...",amazon.com/Resurrection-Walk-Michael-Connelly/...
53,54,Flash Cards: Sight Words,2.88,4.8,Scholastic,2018,"Educational Material, Childrens",amazon.com/Flash-Cards-Scholastic-Teacher-Reso...
54,55,I Love You Like No Otter: A Funny and Sweet An...,5.37,4.9,Rose Rossner,2020,"Picture Books, Animals, Childrens, Fiction, Lo...",amazon.com/Love-You-Like-No-Otter/dp/172821374...
55,56,Chicka Chicka Boom Boom (Board Book),4.32,4.9,"Bill Martin Jr., John Archambault",1989,"Fiction, Alphabet",amazon.com/Chicka-Boom-Board-Book/dp/144245070...
56,57,From Crook to Cook: Platinum Recipes from Tha ...,12.15,4.8,Snoop Dogg,2018,"Cookbooks, Cooking",amazon.com/Crook-Cook-Platinum-Recipes-Kitchen...
59,60,There Was an Old Lady Who Swallowed a Turkey!,6.28,4.8,Lucille Colandro,2016,"Picture Books, Holiday, Childrens, Fiction, St...",amazon.com/There-Was-Lady-Swallowed-Turkey/dp/...
61,62,The Complete Cookbook for Young Chefs: 100+ Re...,9.97,4.8,Americas Test Kitchen Kids,2018,Cookbook,amazon.com/Complete-Cookbook-Young-Chefs/dp/14...
66,67,How to Catch an Elf,6.94,4.8,Adam Wallace,2016,"Christmas, Picture Books, Holiday, Childrens, ...",amazon.com/How-Catch-Elf-Adam-Wallace/dp/14926...
68,69,"Hello, Baby Animals: A Durable High-Contrast B...",4.73,4.9,"duopress labs, Julissa Mora",2016,"Childrens, Picture Books, Animals",amazon.com/Hello-Baby-Animals-High-Contrast-Bo...
71,72,A Court of Mist and Fury (A Court of Thorns an...,12.79,4.8,Sarah J. Maas,2016,"Fantasy, Romance, Young Adult, New Adult, Fiction",amazon.com/Court-Mist-Fury-Thorns-Roses/dp/163...
75,76,Where's Spot?,4.97,4.9,Eric Hill,1980,Childrens,amazon.com/Wheres-Spot-Eric-Hill/dp/0399240462...
79,80,Harry Potter Paperback Box Set (Books 1-7),45.22,4.9,J.K. Rowling,2014,"Childrens, Young Adult, Fantasy, Science Ficti...",amazon.com/Harry-Potter-Paperback-Box-Books/dp...
81,82,If Animals Kissed Good Night,4.19,4.8,Ann Whitford Paul,2008,"Picture Books, Childrens, Animals, Fiction, Fa...",amazon.com/If-Animals-Kissed-Good-Night/dp/037...
83,84,Five Silly Turkeys,5.99,4.8,Salina Yoon,2005,"Picture Books, Childrens, Holiday, Storytime, ...",amazon.com/Five-Silly-Turkeys-Salina-Yoon/dp/0...
84,85,Paint by Sticker Kids: Christmas: Create 10 Pi...,6.06,4.8,Workman Publishing,2019,Childrens Literature,amazon.com/Paint-Sticker-Kids-Workman-Publishi...
87,88,A Court of Wings and Ruin (A Court of Thorns a...,11.56,4.8,Sarah J. Maas,2017,Fantasy,amazon.com/Court-Wings-Ruin-Thorns-Roses/dp/16...
89,90,Harry Potter and the Prisoner of Azkaban (Harr...,25.97,4.9,J.K. Rowling,1999,Fantasy,amazon.com/Harry-Potter-Prisoner-Azkaban-MinaL...
90,91,"Moo, Baa, La La La!",3.69,4.9,Sandra Boynton,1982,"Childrens literature, picture book",amazon.com/Moo-Baa-Sandra-Boynton/dp/067144901...
99,100,The Wonky Donkey,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...

In [98]:
book.loc[book.author.isin(['Craig Smith'])]

,Rank,book title,book price,rating,author,year of publication,genre,url
99,100,The Wonky Donkey,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...

In [100]:
book.loc[book.rating.isin([4.4,4.5])]

,Rank,book title,book price,rating,author,year of publication,genre,url
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
8,9,Killers of the Flower Moon: The Osage Murders ...,9.86,4.4,David Grann,2017,"Nonfiction, True Crime",amazon.com/Killers-Flower-Moon-Osage-Murders/d...
9,10,All the Light We Cannot See: A Novel,11.98,4.5,Anthony Doerr,2014,Historical Fiction,amazon.com/All-Light-We-Cannot-See/dp/15011732...
23,24,A Little Life,11.83,4.5,Hanya Yanagihara,2015,"Fiction, Contemporary, LGBT, Literary Fiction,...",amazon.com/Little-Life-Hanya-Yanagihara/dp/080...
32,33,The Housemaid,8.11,4.5,Don Miguel Ruiz,1997,"Spirituality, self-help, personal growth",amazon.com/Housemaid-Freida-McFadden/dp/153874...
33,34,How to Know a Person: The Art of Seeing Others...,19.89,4.5,Alice Walstead,2022,"Thriller, mystery, suspense",amazon.com/How-Know-Person-Seeing-Others/dp/05...
50,51,Hidden Potential: The Science of Achieving Gre...,21.00,4.4,Adam M. Grant,2023,"Nonfiction, Self Help, Psychology, Business, L...",amazon.com/Hidden-Potential-Science-Achieving-...
69,70,Haunting Adeline (Cat and Mouse Duet),13.36,4.4,H.D. Carlton,2021,"Dark, Thriller, Fantasy, Adult, Contemporary, ...",amazon.com/Haunting-Adeline-Cat-Mouse-Duet/dp/...
82,83,Things We Never Got Over (Knockemout),8.93,4.5,Lucy Score,2022,"Romance, Contemporary, Contemporary Romance, F...",amazon.com/Things-We-Never-Got-Over/dp/1945631...
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...

In [102]:
book.loc[book.author.isnull()]

Empty DataFrame
Columns: [Rank, book title, book price, rating, author, year of publication, genre, url]
Index: []

In [105]:
book['New '] = 'data'
book['New']

0     data
1     data
2     data
3     data
4     data
      ...
95    data
96    data
97    data
98    data
99    data
Name: New, Length: 100, dtype: str

In [106]:
book

,Rank,book title,book price,rating,author,year of publication,genre,url,New,New
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...,data,data
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...,data,data
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...,data,data
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...,data,data
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...,data,data
...,...,...,...,...,...,...,...,...,...,...
95,96,First Little Readers Parent Pack: Guided Readi...,11.40,4.7,Deborah Schecter,2010,Nonfiction,amazon.com/First-Little-Readers-Parent-Pack/dp...,data,data
96,97,Hatchet,5.14,4.7,Gary Paulsen,1987,"young adult novel, adventure novel, survival ...",amazon.com/Hatchet-Gary-Paulsen/dp/1416936475/...,data,data
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...,data,data
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...,data,data
99,100,The Wonky Donkey,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...,data,data

In [108]:
book['my_index'] = range(len(book), 0, -1)
book['my_index']

0     100
1      99
2      98
3      97
4      96
     ...
95      5
96      4
97      3
98      2
99      1
Name: my_index, Length: 100, dtype: int64

In [109]:
book

,Rank,book title,book price,rating,author,year of publication,genre,url,New,New,my_index
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...,data,data,100
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...,data,data,99
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...,data,data,98
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...,data,data,97
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...,data,data,96
...,...,...,...,...,...,...,...,...,...,...,...
95,96,First Little Readers Parent Pack: Guided Readi...,11.40,4.7,Deborah Schecter,2010,Nonfiction,amazon.com/First-Little-Readers-Parent-Pack/dp...,data,data,5
96,97,Hatchet,5.14,4.7,Gary Paulsen,1987,"young adult novel, adventure novel, survival ...",amazon.com/Hatchet-Gary-Paulsen/dp/1416936475/...,data,data,4
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...,data,data,3
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...,data,data,2
99,100,The Wonky Donkey,5.28,4.8,Craig Smith,2009,"Childrens, Picture Books",amazon.com/Wonky-Donkey-Craig-Smith/dp/0545261...,data,data,1