# Pandas summary functions and aggregations

In [2]:
import pandas as pd
import numpy as np

In [80]:
url = "https://raw.githubusercontent.com/vega/vega-datasets/main/data/movies.json"
reviews = pd.read_json(url)
reviews.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes
0,The Land Girls,146083.0,146083.0,NaN,8000000.0,Jun 12 1998,R,NaN,Gramercy,NaN,NaN,NaN,NaN,NaN,6.1,1071.0
1,"First Love, Last Rites",10876.0,10876.0,NaN,300000.0,Aug 07 1998,R,NaN,Strand,NaN,Drama,NaN,NaN,NaN,6.9,207.0
2,I Married a Strange Person,203134.0,203134.0,NaN,250000.0,Aug 28 1998,NaN,NaN,Lionsgate,NaN,Comedy,NaN,NaN,NaN,6.8,865.0
3,Let's Talk About Sex,373615.0,373615.0,NaN,300000.0,Sep 11 1998,NaN,NaN,Fine Line,NaN,Comedy,NaN,NaN,13.0,NaN,NaN
4,Slam,1009819.0,1087521.0,NaN,1000000.0,Oct 09 1998,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,NaN,62.0,3.4,165.0

In [26]:
reviews['IMDB Rating'].describe()

count    2988.000000
mean        6.283467
std         1.252290
min         1.400000
25%         5.600000
50%         6.400000
75%         7.200000
max         9.200000
Name: IMDB Rating, dtype: float64

In [30]:
reviews['IMDB Rating'].unique()

array([6.1, 6.9, 6.8, nan, 3.4, 7.7, 3.8, 5.8, 7. , 7.5, 8.4, 2.5, 8.9,
       8.1, 5.6, 6.3, 7.1, 5.7, 3.2, 6. , 6.4, 7.4, 5.4, 4.9, 7.6, 4.6,
       6.6, 6.7, 7.3, 5.9, 3.7, 8.2, 8.6, 6.2, 5.1, 4.4, 5. , 3.3, 8. ,
       4.8, 7.2, 7.8, 4.3, 8.3, 7.9, 4.1, 5.3, 5.2, 6.5, 4.5, 8.8, 3.5,
       5.5, 4.7, 3.9, 3. , 9. , 9.2, 1.5, 3.6, 2.2, 8.7, 2.6, 8.5, 2.7,
       2.3, 4.2, 4. , 2.8, 2.9, 1.4, 2.1, 1.7, 2.4, 3.1, 1.6, 2. , 9.1])

In [28]:
reviews['IMDB Rating'].mean()

np.float64(6.283467202141901)

In [38]:
reviews.Distributor.describe()

count             2969
unique             174
top       Warner Bros.
freq               318
Name: Distributor, dtype: object

In [39]:
reviews.Distributor.unique()

<ArrowStringArray>
[               'Gramercy',                  'Strand',
               'Lionsgate',               'Fine Line',
                 'Trimark',                     'MGM',
               'Zeitgeist',                 'Artisan',
                       nan,           'Sony Pictures',
 ...
 'Rocky Mountain Pictures',              'Third Rail',
       'Gold Circle Films',               'CBS Films',
           'Film Movement',                'Borotoro',
  'Black Diamond Pictures',            'Tartan Films',
      'The Bigger Picture',   'Oscilloscope Pictures']
Length: 175, dtype: str

In [37]:
reviews['Major Genre'].value_counts()

Major Genre
Drama                  789
Comedy                 675
Action                 420
Adventure              274
Thriller/Suspense      239
Horror                 219
Romantic Comedy        137
Musical                 53
Documentary             43
Western                 36
Black Comedy            36
Concert/Performance      5
Name: count, dtype: int64

In [40]:
reviews['IMDB Rating']

0       6.1
1       6.9
2       6.8
3       NaN
4       3.4
       ...
3196    7.0
3197    NaN
3198    3.4
3199    5.7
3200    6.7
Name: IMDB Rating, Length: 3201, dtype: float64

In [41]:
reviews['IMDB Rating'].mean()

np.float64(6.283467202141901)

In [46]:
review_IMDB_Rating_mean = reviews['IMDB Rating'].mean()
reviews['IMDB Rating'].map(lambda p: p - review_IMDB_Rating_mean)

0      -0.183467
1       0.616533
2       0.516533
3            NaN
4      -2.883467
          ...
3196    0.716533
3197         NaN
3198   -2.883467
3199   -0.583467
3200    0.416533
Name: IMDB Rating, Length: 3201, dtype: float64

In [84]:
us_gross_mean = reviews['US Gross'].mean()

def remean_us_gross(row):
    row['US Gross'] = row['US Gross'] - us_gross_mean
    row['Worldwide Gross'] = row['Worldwide Gross'] + row['Worldwide Gross'] * 0.2
    return row
    
reviews = reviews.apply(remean_us_gross, axis='columns')
reviews.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes
0,The Land Girls,-4.385600e+07,3.029177e+05,NaN,8000000.0,Jun 12 1998,R,NaN,Gramercy,NaN,NaN,NaN,NaN,NaN,6.1,1071.0
1,"First Love, Last Rites",-4.399121e+07,2.255247e+04,NaN,300000.0,Aug 07 1998,R,NaN,Strand,NaN,Drama,NaN,NaN,NaN,6.9,207.0
2,I Married a Strange Person,-4.379895e+07,4.212187e+05,NaN,250000.0,Aug 28 1998,NaN,NaN,Lionsgate,NaN,Comedy,NaN,NaN,NaN,6.8,865.0
3,Let's Talk About Sex,-4.362847e+07,7.747281e+05,NaN,300000.0,Sep 11 1998,NaN,NaN,Fine Line,NaN,Comedy,NaN,NaN,13.0,NaN,NaN
4,Slam,-4.299227e+07,2.255084e+06,NaN,1000000.0,Oct 09 1998,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,NaN,62.0,3.4,165.0

In [60]:
reviews.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes
0,The Land Girls,146083.0,146083.0,NaN,8000000.0,Jun 12 1998,R,NaN,Gramercy,NaN,NaN,NaN,NaN,NaN,6.1,1071.0
1,"First Love, Last Rites",10876.0,10876.0,NaN,300000.0,Aug 07 1998,R,NaN,Strand,NaN,Drama,NaN,NaN,NaN,6.9,207.0
2,I Married a Strange Person,203134.0,203134.0,NaN,250000.0,Aug 28 1998,NaN,NaN,Lionsgate,NaN,Comedy,NaN,NaN,NaN,6.8,865.0
3,Let's Talk About Sex,373615.0,373615.0,NaN,300000.0,Sep 11 1998,NaN,NaN,Fine Line,NaN,Comedy,NaN,NaN,13.0,NaN,NaN
4,Slam,1009819.0,1087521.0,NaN,1000000.0,Oct 09 1998,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,NaN,62.0,3.4,165.0

In [61]:
review_IMDB_Rating_mean = reviews['IMDB Rating'].mean()
reviews['IMDB Rating']- review_IMDB_Rating_mean

0      -0.183467
1       0.616533
2       0.516533
3            NaN
4      -2.883467
          ...
3196    0.716533
3197         NaN
3198   -2.883467
3199   -0.583467
3200    0.416533
Name: IMDB Rating, Length: 3201, dtype: float64

In [74]:
reviews['Major Genre'] + " - " + reviews['Creative Type']

0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4            Drama - Contemporary Fiction
                      ...
3196        Comedy - Contemporary Fiction
3197    Thriller/Suspense - Dramatization
3198               Adventure - Super Hero
3199       Adventure - Historical Fiction
3200       Adventure - Historical Fiction
Length: 3201, dtype: str